# Generated by Django 6.0.1 on 2026-02-20 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDay',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
            ],
            options={
                'verbose_name': 'Hari Perjalanan',
                'verbose_name_plural': 'Hari Perjalanan',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Booking ID')),
                ('trip_id_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Trip ID (ref)')),
                ('participant_name', models.CharField(max_length=255, verbose_name='Nama Peserta')),
                ('status_code', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUND_REQUESTED', 'Refund Requested')], default='PENDING', max_length=30, verbose_name='Status')),
                ('status_description', models.TextField(blank=True, default='', verbose_name='Deskripsi Status')),
                ('transaction_id_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID (ref)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Disinkronkan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('booking_id_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Booking ID (ref)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Pembayaran')),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=30, verbose_name='Status Pembayaran')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipe Pembayaran')),
                ('payment_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider Pembayaran')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Disinkronkan')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gateway.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(verbose_name='Waktu Selesai')),
                ('deskripsi', models.CharField(max_length=500, verbose_name='Deskripsi')),
                ('lokasi_nama', models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Lokasi')),
                ('lokasi_alamat', models.CharField(blank=True, default='', max_length=500, verbose_name='Alamat')),
                ('lokasi_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lokasi_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gateway.travelday')),
            ],
            options={
                'verbose_name': 'Aktivitas',
                'verbose_name_plural': 'Aktivitas',
                'ordering': ['waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Rencana')),
                ('durasi_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('durasi_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('anggaran_jumlah', models.FloatField(verbose_name='Anggaran (jumlah)')),
                ('anggaran_mata_uang', models.CharField(default='IDR', max_length=10, verbose_name='Mata Uang')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Disinkronkan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rencana Perjalanan',
                'verbose_name_plural': 'Rencana Perjalanan',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddField(
            model_name='travelday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='gateway.travelplan'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('deskripsi', models.CharField(max_length=500, verbose_name='Deskripsi')),
                ('tanggal_pengeluaran', models.DateField(verbose_name='Tanggal Pengeluaran')),
                ('biaya_jumlah', models.FloatField(verbose_name='Biaya (jumlah)')),
                ('biaya_mata_uang', models.CharField(default='IDR', max_length=10, verbose_name='Mata Uang')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='gateway.travelplan')),
            ],
            options={
                'verbose_name': 'Pengeluaran',
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['tanggal_pengeluaran'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Trip ID')),
                ('trip_name', models.CharField(max_length=255, verbose_name='Nama Trip')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia?')),
                ('guide_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Guide')),
                ('itinerary_destinations', models.JSONField(blank=True, null=True, verbose_name='Destinasi Itinerary')),
                ('itinerary_description', models.TextField(blank=True, default='', verbose_name='Deskripsi Itinerary')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Disinkronkan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='gateway.trip'),
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('location', models.CharField(max_length=500, verbose_name='Lokasi')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gateway.trip')),
            ],
            options={
                'verbose_name': 'Jadwal Trip',
                'verbose_name_plural': 'Jadwal Trip',
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='travelday',
            unique_together={('plan', 'tanggal')},
        ),
    ]
